### ISSUE TITLE
License

### ISSUE THREAD

**Issue by StianHB** [Lars-Saetaberget/Hipchat-gifcompressor#2]
There is no license with this project, so I can't set it up on our enterprise network.

Could you add one to the project?

**Comment by Lars-Saetaberget** [comment]
Solved in https://github.com/Lars-Saetaberget/Hipchat-gifcompressor/commit/d17680e65e81ed925af4d10cd2138d27b11ec4e4
Thank you so much for your valuable input, and for supporting this project.
